spring:
  application:
    name: "CDYT API"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
      # Enable JPA Auditing
      auditing:
        enable: true
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      # password: ${SPRING_REDIS_PASSWORD:}

# Security settings
jwt:
  secret: ${JWT_SECRET}
  expiration-days: ${JWT_DATABASE_EXPIRATION_DAYS:1} # Normal login: 1 day
  expiration-remember-days: ${JWT_DATABASE_EXPIRATION_REMEMBER_DAYS:7} # Remember me: 7 days
  expiration: ${JWT_EXPIRATION:2592000} # JWT internal expiration: 30 days in seconds (not used for validation)

# Authentication optimization settings
auth:
  cache:
    enabled: true
    ttl-minutes: 5
    max-size: 1000
  filter:
    skip-public-paths: true
    public-paths:
      - "/api/auth/"
      - "/swagger-ui/"
      - "/v3/api-docs/"
      - "/webjars/"
      - "/actuator/health"

viewcount:
  sync:
    limit: ${VIEWCOUNT_SYNC_LIMIT}
